http:
  routers:
    easy-wms:
      entrypoints:
        - http
      service: easywms
      rule: Host(`abc.lkkus.app`)

  services:
    easywms:
      loadBalancer:
        servers:
          - url: https://wms.easywms.app
        passHostHeader: false