http:
  routers:
    easywms:
      entryPoints:
        - "http"
        - "https"
      rule: "Host(`lkkus.app`)"
      tls: {}
      service: easywms

  services:
    easywms:
      loadBalancer:
        servers:
          - url: https://www.0degreect.com
        passHostHeader: false