http:
  #region routers
  routers:
    easywms:
      entryPoints:
        - "https"
      rule: "Host(`abc.lkkus.app`)"
      middlewares:
        - https-redirectscheme
      tls: {}
      service: easywms

  #endregion
  #region services
  services:
    easywms:
      loadBalancer:
        servers:
          - url: "https://wms.easywms.app"
        passHostHeader: false
  #endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true