http:
  #region routers
  routers:
    easywms:
      entryPoints:
        - "https"
      rule: "Host(`abc.lkkus.app`)"
      middlewares:
        - gzip
        - redirect-to-https
        - testHeader
      tls: {}
      service: easywms

  #endregion
  #region services
  services:
    easywms:
      loadBalancer:
        servers:
          - url: "http://129.80.104.229"
        passHostHeader: true
  #endregion
  middlewares:
    testHeader:
      headers:
        customRequestHeaders:
          X-Forwarded-Host: "wms.easywms.app" # Adds
        customResponseHeaders:
          X-Custom-Response-Header: "value" # Remove
    redirect-to-https:
      redirectScheme:
        scheme: https
    gzip:
      compress: true