http:
  routers:
    netlify:
      entryPoints:
        - "https"
      rule: "Host(`demo.lkkus.app`)"
      tls: true
      service: netlify

    demo:
      entryPoints:
        - "https"
      rule: "Host(`dingsheng.lkkus.app`)"
      tls: true
      service: demo

  services:
    netlify:
      loadBalancer:
        servers:
          - url: "https://imaginative-meerkat-397e19.netlify.app" #SSG website hosting via netlify
        passHostHeader: true

    demo:
      loadBalancer:
        servers:
          - url: "https://prosperity-construction.ezsite.app/" #SSG website hosting via netlify
        passHostHeader: true

  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        period: 1
        burst: 100