http:
  routers:
    easy-wms:
      entryPoints:
        - "http"
        - "https"
      rule: "Host(`abc.lkkus.app`)"
      middlewares:
        - redirect-to-https
      tls: {}
      service: easywms

  services:
    easywms:
      loadBalancer:
        servers:
          - url: "https://129.80.104.229:9443"
        passHostHeader: true

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

tls:
  options:
    default:
      #sniStrict: true # prevents leaking default cert; see https://doc.traefik.io/traefik/v2.2/https/tls/#strict-sni-checking
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305