http:
  routers:
    routers:
      dashboard:
        entryPoints:
          - "websecure"
          - "other"
        rule: Host(`${TRAEFIK_DASHBOARD_HOST}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        service: api@internal
    easy-wms:
      entrypoints:
        - http
      service: easywms
      rule: Host(`abc.lkkus.app`)

  services:
    easywms:
      loadBalancer:
        servers:
          - url: https://wms.easywms.app
        passHostHeader: false