http:
  routers:
    netlify:
      entryPoints:
        - "http"
        - "https"
      rule: "Host(`lkkus.app`)"
      tls: {}
      service: netlify

  services:
    netlify:
      loadBalancer:
        servers:
          - url: https://go.bychronos.com/l/testing1234/ #SSG website hosting via netlify
        passHostHeader: false