http:
  routers:
    netlify:
      entryPoints:
        - "https"
      rule: "Host(`demo.lkkus.app`)"
      tls: {}
      service: netlify

  services:
    netlify:
      loadBalancer:
        servers:
          - url: "https://imaginative-meerkat-397e19.netlify.app" #SSG website hosting via netlify
        passHostHeader: false

  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        period: 1
        burst: 100

  # allow self-signed certificates for proxied web services
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true