http:
  routers:
    netlify:
      entryPoints:
        - "http"
        - "https"
      rule: "Host(`aaa.lkkus.app`)"
      tls: {}
      service: netlify

  services:
    netlify:
      loadBalancer:
        servers:
          - url: https://easywms.app #SSG website hosting via netlify
        passHostHeader: true