http:
  routers:
    dashboard:
      rule: Host(`traffic.lkkus.app`)
      entryPoints:
        - "https"
      middlewares:
        - traefik-auth
        - default-headers
        - https-redirects
      service: api@internal
    easy-wms:
      rule: Host(`abc.lkkus.app`)
      entryPoints:
        - "https"
      service: easywms

  services:
    easywms:
      loadBalancer:
        servers:
          - url: https://wms.easywms.app
        passHostHeader: true

  middlewares:
    traefik-auth:
      basicAuth:
        users:
          - "username:$2y$05$DBZNAuQXry6I9mtSKfrRQO975oGev0dzwaJd8qtuVTaSCLRDIABYi"
    https-redirects:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https