http:
  routers:
    netlify:
      entryPoints:
        - "https"
      rule: "Host(`lkkus.app`)"
      tls: {}
      service: netlify

  services:
    netlify:
      loadBalancer:
        servers:
          - url: "https://go.bychronos.com/l/demo802304/" #SSG website hosting via netlify
        passHostHeader: false

  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        period: 1
        burst: 100