http:
  routers:
    easywms:
      entryPoints:
        - "http"
        - "https"
      rule: "Host(`abc.lkkus.app`)"
      tls: {}
      service: easywms

  services:
    easywms:
      loadBalancer:
        servers:
          - url: https://wms.easywms.app
        passHostHeader: true