http:
  routers:
    easywms:
      entryPoints:
        - "https"
      rule: "Host(`abc.lkkus.app`)"
      middlewares:
        - testHeader
      tls: {}
      service: easywms

  services:
    easywms:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "http://129.80.104.229:80"
        passHostHeader: true

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true

  middlewares:
    testHeader:
      headers:
        customRequestHeaders:
          X-Forwarded-Host: "wms.easywms.app" # Adds
        customResponseHeaders:
          X-Custom-Response-Header: "value" # Remove

    redirect-to-https:
      redirectScheme:
        scheme: https

tls:
  options:
    default:
      #sniStrict: true # prevents leaking default cert; see https://doc.traefik.io/traefik/v2.2/https/tls/#strict-sni-checking
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305