http:
  routers:
    routers:
      dashboard:
        entryPoints:
          - "https"
        rule: Host(`${TRAEFIK_DASHBOARD_HOST}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        service: api@internal
    easy-wms:
      entryPoints:
        - "https"
      middlewares:
        - traefik-auth
        - default-headers
        - https-redirect
      service: easywms
      rule: Host(`abc.lkkus.app`)

  services:
    easywms:
      loadBalancer:
        servers:
          - url: https://wms.easywms.app
        passHostHeader: true

  middlewares:
    traefik-auth:
      basicAuth:
        users:
          - ${TRAEFIK_DASHBOARD_CREDENTIALS}
    https-redirects:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https