http:
  routers:
    easy-wms:
      entryPoints:
        - "http"
        - "https"
      rule: "Host(`abc.lkkus.app`)"
      middlewares:
        - redirect-to-https
      tls: {}
      service: easywms

  services:
    easywms:
      loadBalancer:
        servers:
          - url: "https://www.go3pos.com"

  middlewares:
    testHeader:
      headers:
        customResponseHeaders: # field names are case-insensitive
          #X-Robots-Tag: "all,noarchive,nosnippet,notranslate,noimageindex"
          Server: "" # prevent version disclosure
          X-Powered-By: "" # prevent version disclosure
          X-Forwarded-Proto: "https"
          #Permissions-Policy: "accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(), gamepad=(), geolocation=(), gyroscope=(), hid=(), identity-credentials-get=(), idle-detection=(), local-fonts=(), magnetometer=(), microphone=(), midi=(), otp-credentials=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), storage-access=(), usb=(), web-share=(), window-management=(), xr-spatial-tracking=()"
          #Cross-Origin-Embedder-Policy: "unsafe-none"
          #Cross-Origin-Opener-Policy: "same-origin"
          #Cross-Origin-Resource-Policy: "same-site"
          sslProxyHeaders:
            X-Forwarded-Proto: "https"
          hostsProxyHeaders:
            X-Forwarded-Host: "wms.easywms.app"
          customRequestHeaders:
            X-Forwarded-Proto: "https"
          contentTypeNosniff: true # X-Content-Type-Options
          customFrameOptionsValue: "SAMEORIGIN" # X-Frame-Options
          browserXssFilter: false # X-XSS-Protection; deprecated
          referrerPolicy: "strict-origin-when-cross-origin" # Referrer-Policy
          forceSTSHeader: true # HTTP-Strict-Transport-Security (HSTS)
          stsIncludeSubdomains: true # HTTP-Strict-Transport-Security (HSTS)
          stsSeconds: 63072000 # HTTP-Strict-Transport-Security (HSTS)
          stsPreload: true # HTTP-Strict-Transport-Security (HSTS)

    redirect-to-https:
      redirectScheme:
        scheme: https

tls:
  options:
    default:
      #sniStrict: true # prevents leaking default cert; see https://doc.traefik.io/traefik/v2.2/https/tls/#strict-sni-checking
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305