http:
  #region routers
  routers:
    easywms:
      entryPoints:
        - "https"
      rule: "Host(`abc.lkkus.app`)"
      middlewares:
        - https-redirectscheme
      service: easywms

  #endregion
  #region services
  services:
    easywms:
      loadBalancer:
        servers:
          - url: "https://wms.easywms.app"
        passHostHeader: true
  #endregion
  middlewares:
    testHeader:
      headers:
        customRequestHeaders:
          X-Forwarded-Host: "wms.easywms.app" # Adds
        customResponseHeaders:
          X-Custom-Response-Header: "value" # Remove
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true