http:
  routers:
    netlify:
      entryPoints:
        - "https"
      rule: "Host(`lkkus.app`)"
      tls: {}
      service: netlify
      middlewares:
        - "add-foo"

  services:
    netlify:
      loadBalancer:
        servers:
          - url: "https://go.bychronos.com/" #SSG website hosting via netlify
        passHostHeader: false

  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        period: 1
        burst: 100

    add-foo:
      addPrefix:
        prefix: "/l/demo802304"