version: "3.7"
networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:v2.10
    container_name: "traefik"
    restart: always
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      # Uncomment for debug
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.auth:/auth/traefik.auth
    command:
     # # Uncomment for debug
     # - --api.insecure=true
      - --entrypoints.web.address=:80
     #- "--log.level=DEBUG"
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=${LETS_ENCRYPT_EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json