#!/usr/bin/env bash

# Inspired on https://github.com/adriancooney/Taskfile
#
# Install an alias, to be able to simply execute `run`
# echo 'alias run=./run' >> ~/.aliases
#
# alias run=./Taskfile
# alias help=./Taskfile help

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function default {
    help
}

function copyCompose {
  cp docker-compose.prod.yml docker-compose.yml
}

function afterFreshInstall {
  docker network ls | grep web || docker network create web
  cp .env.example .env
}

function auth {
  docker run --rm --entrypoint htpasswd httpd:2 -Bbn $1 $2 > traefik.auth
}

function baseDeployScript {
    cd /home/forge/traefik

    # We assume Docker has already been installed using the "Install Docker and Docker-Compose" recipe.
    # The "Make .env variables available to deploy script" must be checked in Laravel Forge

    # Confirm Docker is installed and available
    if ! command -v docker &> /dev/null; then
        echo "Docker is not installed. Please install Docker and try again."
        exit 1
    fi

    echo "Deploying Traefik at ${TRAEFIK_DASHBOARD_HOST}"
    echo "commit @${FORGE_DEPLOY_COMMIT} -- ${FORGE_DEPLOY_MESSAGE}"

    if [[ $FORGE_MANUAL_DEPLOY -eq 1 ]]; then
        echo "This deploy was triggered manually."
    fi

    git pull origin $FORGE_SITE_BRANCH

    # Create the 'proxy' network, if it doesn't already exist
    echo "Creating the proxy network if it does not already exist"
    docker network ls | grep proxy || docker network create proxy

    # Use the docker-compose.prod.yml file to spin up the service
    echo "Docker up with docker-compose.yml.\n"
    docker-compose up -d --force-recreate

    echo "Deployment complete."
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"